// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LargeNumber.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from LargeNumber.proto</summary>
  public static partial class LargeNumberReflection {

    #region Descriptor
    /// <summary>File descriptor for LargeNumber.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LargeNumberReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMYXJnZU51bWJlci5wcm90bxIFcHJvdG8iSgoLTGFyZ2VOdW1iZXISEQoJ",
            "SW50TnVtYmVyGAEgASgFEhIKCkxvbmdOdW1iZXIYAiABKAMSFAoMU3RyaW5n",
            "TnVtYmVyGAMgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.LargeNumber), global::Proto.LargeNumber.Parser, new[]{ "IntNumber", "LongNumber", "StringNumber" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LargeNumber : pb::IMessage<LargeNumber>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LargeNumber> _parser = new pb::MessageParser<LargeNumber>(() => new LargeNumber());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LargeNumber> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.LargeNumberReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LargeNumber() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LargeNumber(LargeNumber other) : this() {
      intNumber_ = other.intNumber_;
      longNumber_ = other.longNumber_;
      stringNumber_ = other.stringNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LargeNumber Clone() {
      return new LargeNumber(this);
    }

    /// <summary>Field number for the "IntNumber" field.</summary>
    public const int IntNumberFieldNumber = 1;
    private int intNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IntNumber {
      get { return intNumber_; }
      set {
        intNumber_ = value;
      }
    }

    /// <summary>Field number for the "LongNumber" field.</summary>
    public const int LongNumberFieldNumber = 2;
    private long longNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LongNumber {
      get { return longNumber_; }
      set {
        longNumber_ = value;
      }
    }

    /// <summary>Field number for the "StringNumber" field.</summary>
    public const int StringNumberFieldNumber = 3;
    private string stringNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringNumber {
      get { return stringNumber_; }
      set {
        stringNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LargeNumber);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LargeNumber other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IntNumber != other.IntNumber) return false;
      if (LongNumber != other.LongNumber) return false;
      if (StringNumber != other.StringNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IntNumber != 0) hash ^= IntNumber.GetHashCode();
      if (LongNumber != 0L) hash ^= LongNumber.GetHashCode();
      if (StringNumber.Length != 0) hash ^= StringNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IntNumber != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IntNumber);
      }
      if (LongNumber != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LongNumber);
      }
      if (StringNumber.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StringNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IntNumber != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IntNumber);
      }
      if (LongNumber != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LongNumber);
      }
      if (StringNumber.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StringNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IntNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntNumber);
      }
      if (LongNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LongNumber);
      }
      if (StringNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LargeNumber other) {
      if (other == null) {
        return;
      }
      if (other.IntNumber != 0) {
        IntNumber = other.IntNumber;
      }
      if (other.LongNumber != 0L) {
        LongNumber = other.LongNumber;
      }
      if (other.StringNumber.Length != 0) {
        StringNumber = other.StringNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IntNumber = input.ReadInt32();
            break;
          }
          case 16: {
            LongNumber = input.ReadInt64();
            break;
          }
          case 26: {
            StringNumber = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IntNumber = input.ReadInt32();
            break;
          }
          case 16: {
            LongNumber = input.ReadInt64();
            break;
          }
          case 26: {
            StringNumber = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
